#!/usr/bin/env python3
#
# app/dispatch/base.py
# Copyright (C) 2026 Gill-Bates http://github.com/Gill-Bates
#

"""Ports for the battery dispatch domain (REQ-001)."""

from typing import Protocol

from app.dispatch.capabilities import CapabilityRecord
from app.dispatch.models import (
    ControlTelemetry,
    DeviceControlSnapshot,
    DeviceLimits,
    DispatchCommand,
    DispatchStatus,
    PowerSetpoint,
)
from app.gateway.base import WriteOutcome


class BatteryDispatchPort(Protocol):
    async def submit(self, device_id: str, command: DispatchCommand) -> DispatchStatus: ...
    async def status(self, device_id: str) -> DispatchStatus: ...
    async def cancel(self, device_id: str) -> DispatchStatus: ...
    async def tick(self, device_id: str) -> DispatchStatus: ...
    async def recover(self) -> None: ...
    async def run(self, device_id: str) -> None: ...
    async def shutdown_restore(self) -> None: ...
    # The port is the only writer of the dispatch database; both writes are async because they
    # fsync, and both take effect in memory only after the commit succeeded.
    async def set_capability(self, device_id: str, record: CapabilityRecord) -> None: ...
    async def set_device_limits(self, device_id: str, limits: DeviceLimits) -> None: ...
    def capabilities(self, device_id: str) -> tuple[CapabilityRecord, ...]: ...
    def device_limits(self, device_id: str) -> DeviceLimits | None: ...


class BatteryDispatchGateway(Protocol):
    async def read_control_telemetry(self, device_id: str) -> ControlTelemetry: ...
    async def read_snapshot(self, device_id: str) -> DeviceControlSnapshot: ...
    async def read_soc(self, device_id: str) -> float: ...
    async def apply_setpoint(self, device_id: str, setpoint: PowerSetpoint) -> WriteOutcome: ...
    async def apply_soc_target(self, device_id: str, percent: float) -> WriteOutcome: ...
    async def apply_control_mode(self, device_id: str, *, external: bool) -> WriteOutcome: ...
    async def apply_grid_charge(self, device_id: str, *, enabled: bool) -> WriteOutcome: ...
    async def restore(self, device_id: str, snapshot: DeviceControlSnapshot, step: int) -> WriteOutcome: ...
    def required_metric_names(self) -> tuple[str, ...]: ...
