#!/usr/bin/env python3
#
# app/dispatch/base.py
# Copyright (C) 2026 Gill-Bates http://github.com/Gill-Bates
#

"""Ports for the battery dispatch domain (REQ-001)."""

from typing import Protocol

from app.dispatch.capabilities import CapabilityRecord
from app.dispatch.models import (
    ControlTelemetry,
    DeviceControlSnapshot,
    DeviceLimits,
    DispatchCommand,
    DispatchMode,
    DispatchStatus,
    PowerSetpoint,
)
from app.dispatch.soc_policy import SocTargetPolicy
from app.gateway.base import WriteOutcome


class BatteryDispatchPort(Protocol):
    async def submit(self, device_id: str, command: DispatchCommand) -> DispatchStatus: ...
    async def status(self, device_id: str) -> DispatchStatus: ...
    async def cancel(self, device_id: str) -> DispatchStatus: ...
    async def tick(self, device_id: str) -> DispatchStatus: ...
    async def recover(self) -> None: ...
    async def run(self, device_id: str) -> None: ...
    async def shutdown_restore(self) -> None: ...
    # The port is the only writer of the dispatch database; both writes are async because they
    # fsync, and both take effect in memory only after the commit succeeded.
    async def set_capability(self, device_id: str, record: CapabilityRecord) -> None: ...
    async def set_capabilities(self, device_id: str, records: list[CapabilityRecord]) -> None: ...
    async def set_device_limits(self, device_id: str, limits: DeviceLimits) -> None: ...
    # The device id stays a separate positional parameter even though the policy carries one: the
    # port checks the two against each other, so a router that reads the id from the path and the
    # policy from the body cannot persist it under the wrong device.
    async def set_soc_target_policy(self, device_id: str, policy: SocTargetPolicy) -> None: ...
    def capabilities(self, device_id: str) -> tuple[CapabilityRecord, ...]: ...
    def device_limits(self, device_id: str) -> DeviceLimits | None: ...
    def soc_target_policy(self, device_id: str) -> SocTargetPolicy: ...


class BatteryDispatchGateway(Protocol):
    async def read_control_telemetry(self, device_id: str) -> ControlTelemetry: ...
    async def read_snapshot(self, device_id: str) -> DeviceControlSnapshot: ...
    async def read_soc(self, device_id: str) -> float: ...
    async def apply_setpoint(self, device_id: str, setpoint: PowerSetpoint) -> WriteOutcome: ...
    # The caller hands over the business stop goal, the mode and the measured SoC; what register
    # value that implies is the adapter's decision (design 2.5.2/2.5.4).
    async def apply_soc_target(
        self,
        device_id: str,
        *,
        dispatch_mode: DispatchMode,
        stop_target_percent: float,
        soc_percent: float,
    ) -> WriteOutcome: ...
    async def apply_control_mode(self, device_id: str, *, external: bool) -> WriteOutcome: ...
    async def apply_grid_charge(self, device_id: str, *, enabled: bool) -> WriteOutcome: ...
    async def restore(self, device_id: str, snapshot: DeviceControlSnapshot, step: int) -> WriteOutcome: ...
    def required_metric_names(self) -> tuple[str, ...]: ...
